# --- VIKTIG: Endre disse to linjene til din GitHub-info ---
owner: superduperstian # F.eks. "boppel-as"
repo: upptime          # F.eks. "uptime-monitor"

sites:
  - name: Boppel Monitorering (Uptime Kuma)
    url: https://uptimekuma.boppel.no/
    # Sjekker at Uptime Kuma svarer 200 OK (login-siden)
    expectedStatusCodes: [200]
    # Sjekker hvert 5. minutt (standard for Upptime)
    icon: https://uptimekuma.boppel.no/icon.svg

status-website:
  # Hvis du senere vil ha f.eks status.boppel.no, legg det inn her:
  # cname: status.boppel.no
  
  # Hvis du IKKE bruker cname, må denne matche repo-navnet ditt (f.eks /uptime-monitor)
  baseUrl: /upptime
  
  name: Boppel Status
  logoUrl: https://boppel.no/favicon.ico # Endre gjerne til din egen logo-URL
  introTitle: "**Boppel** Systemstatus"
  introMessage: Denne siden overvåker vår infrastruktur. Hvis denne siden viser feil, er hovedserveren vår nede.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Varsling oppsett (Se instruks under koden for hvordan dette virker)
# Du kan fjerne kommentarene (#) under når du har lagt inn "Secrets" i GitHub.
# notifications:
#   - type: slack
#     service_url: ${{ secrets.SLACK_WEBHOOK_URL }}
#   - type: email
#     service_url: ${{ secrets.EMAIL_SMTP_URL }}
